i = imread('autumn.tif');
[xi,yi] = meshgrid(1:0.1:345,1:0.1:206);
anear(:,:,1) = uint8(interp2(double(i(:,:,1)),xi,yi,'nearest'));
anear(:,:,2) = uint8(interp2(double(i(:,:,2)),xi,yi,'nearest'));
anear(:,:,3) = uint8(interp2(double(i(:,:,3)),xi,yi,'nearest'));
alinear(:,:,1) = uint8(interp2(double(i(:,:,1)),xi,yi,'linear'));
alinear(:,:,2) = uint8(interp2(double(i(:,:,2)),xi,yi,'linear'));
alinear(:,:,3) = uint8(interp2(double(i(:,:,3)),xi,yi,'linear'));
aspline(:,:,1) = uint8(interp2(double(i(:,:,1)),xi,yi,'spline'));
aspline(:,:,2) = uint8(interp2(double(i(:,:,2)),xi,yi,'spline'));
aspline(:,:,3) = uint8(interp2(double(i(:,:,3)),xi,yi,'spline'));
figure,imshow(i),figure,imshow(anear),figure,imshow(alinear),figure,imshow(aspline);
i2= imread('serraangel.jpg');
oldSize = size(i2); 
ratio = 0.25;
newSize = max(floor(ratio.*oldSize(1:2)),1);
xi = ((1:newSize(2))-0.5)./ratio+0.5;
yi = ((1:newSize(1))-0.5)./ratio+0.5;
snear(:,:,1) = uint8(interp2(double(i2(:,:,1)),xi,yi(:),'nearest'));
snear(:,:,2) = uint8(interp2(double(i2(:,:,2)),xi,yi(:),'nearest'));
snear(:,:,3) = uint8(interp2(double(i2(:,:,3)),xi,yi(:),'nearest'));
slinear(:,:,1) = uint8(interp2(double(i2(:,:,1)),xi,yi(:),'linear'));
slinear(:,:,2) = uint8(interp2(double(i2(:,:,2)),xi,yi(:),'linear'));
slinear(:,:,3) = uint8(interp2(double(i2(:,:,3)),xi,yi(:),'linear'));
sspline(:,:,1) = uint8(interp2(double(i2(:,:,1)),xi,yi(:),'spline'));
sspline(:,:,2) = uint8(interp2(double(i2(:,:,2)),xi,yi(:),'spline'));
sspline(:,:,3) = uint8(interp2(double(i2(:,:,3)),xi,yi(:),'spline'));
figure,imshow(i2),figure,imshow(snear),figure,imshow(slinear),figure,imshow(sspline);